### ISSUE TITLE
Theoretical consistency

### ISSUE THREAD

**Issue by cshen6** [neurodata/Multiscale-Network-Test#1]
Important:
- [x] we are showing the diffusion process U is exchangeable, thus conditional iid. Therefore we are testing independence of the diffusion process with the nodal attributes. Make that part more explicit in intro, tell people why diffusion process is more advantageous than anything else (add citation too). 
- [x] There is still a gap from condition i.i.d. of U, to dCov(U,X)=0 if and only if U and X is independent. Let us think about it. 

Tentative:
- [ ] extend exchangeability of U to the diffusion distance for the directed and/or weighted graph.
- [x] compare to and think about the case when we replace U by A.

**Comment by cshen6** [comment]
Main:
- [x] theorem x: 
  distance correlation on exchangeable random variables converge to 0 if and only if under independence.

Proof forward: most of thm1 and thm2 holds directly without iid (in dcorr07), so the only step to justify is the SLLN for v-statistic in thm 2.

Carefully check through the SLLN for exchangeable random variables & the V-statistic. Need finite first moment in SLLN for conditional iid, I think.
- [x] corollary: MGC and Dcorr are consistent, when testing network dependency for the euclidean distance of the diffusion map, or Euclidean distance of the adjacency matrix, or the estimated network factors, because they are all exchangeable.

Also need finite second moment above; and note that the adjacency matrix is 2-array joint exchangeable. 

What about directed & weighted graph model?

**Comment by youjin1207** [comment]
@cshen6 Some useful properties valid for exchangeable variables are actually proven in http://www.sciencedirect.com/science/article/pii/S0047259X13000262.

**Comment by cshen6** [comment]
@youjin1207 
yes indeed! although it is for coordinate exchangeability (dimension-wise), rather than observation exchangeability (sample-wise).

**Comment by youjin1207** [comment]
@cshen6 On page 6, they actually mentioned sample exchangeability, even though they didn't specifically prove it. In my understanding, we apply conditional CLT for conditionally independence random variables. I don't know if we actually have to PROVE it, since the results are already there - I don't see the difference between Theorem in my current draft and conditional CLT - instead of sub-sigma-algebra notion, I used g function or eta.

**Comment by cshen6** [comment]
@youjin1207 
I listed the forward and backward directions above for thm X, which is the last theoretical piece. 
Either way, it will lead to proving the theorem and the corollary.

**Comment by youjin1207** [comment]
@cshen6  Now I don't think distance in conditional variable and that in un-conditional variable are the same so we cannot approach in that way.

**Comment by cshen6** [comment]
ok I will think about it before our next meeting.

also, I think adjacency matrix is in fact exchangeable, if we look at the definition and let the exchangeability to be defined on both row and column of the adjacency matrix.
