### ISSUE TITLE
issue post practice talk 

### ISSUE THREAD

**Issue by cshen6** [neurodata/Multiscale-Network-Test#20]
- [x] always try to use one colorbar in multiple panels. If too much formatting, wait til your exam is over.
- [x] I also like the brain graph figure, maybe use that in MGC graph paper intro as well?
- [x] upload your updated figures into the paper, so I can take a look and polish intro?

per your slides:
- [x] change some or most sentences into bullet points, per my MGC slides (will send over email)
- [x] future research: node contribution, optimize over t. Make sure you ask me on Monday if you have any question on them?
- [x] write out global dcov / MGC formulation in a slide.

**Comment by youjin1207** [comment]
In most cases, the range of heatmaps are too much diverse -- except for p-value/power heatmap.. 
<img width="899" alt="heatmap" src="https://cloud.githubusercontent.com/assets/10090016/20636532/aa5c0422-b33c-11e6-8fea-4c32cb072120.png">

**Comment by cshen6** [comment]
Yes agreed!

But make the colorbar fonts larger to usual text font size; now it is too
small.
And we probably don't need the vertical part of the colorbar (i.e., the
distribution), as it is not necessary for our story here.
