### ISSUE TITLE
Political network

### ISSUE THREAD

**Issue by youjin1207** [neurodata/Multiscale-Network-Test#24]
- [x] draw node contribution bar graph as a decreasing order within the group.
- [x] draw a grouped adjacency matrix and see what lead to negative contribution (especially science group.)

**Comment by youjin1207** [comment]
@jovo @cshen6 What do you think about these two figures? I think the significantly negative contribution might be attributed to (a) concentrating edges between particular X (types) or (b) having lots of relationship across groups. You can see the latter case in the second period, the last Party (green).
[outline_polipart.pdf](https://github.com/neurodata/Multiscale-Network-Test/files/632863/outline_polipart.pdf)

**Comment by cshen6** [comment]
yes the adjacency matrix is very informative.

The strong negativity comes from the fact that SC does not contact much
with other groups at all in the first period, so their contribution is
(very negative cross group distance by network * positive cross group
distance by label)= very negative contribution.

Say, if you manually fill up some links between SC and other groups, the SC
contribution should be a lot closer to 0.

Although this example is saying that strong negativity is also useful for
identifying some dependency signal, I guess? This can be true, depending on
how we have ranked & centered.

**Comment by cshen6** [comment]
I recall that if we do absolute contribution, the simulation is also
consistent for node contribution, right?

**Comment by jovo** [comment]
Can we simulate to obtain this effect?
A synthetic data analysis type result?

**Comment by youjin1207** [comment]
Yes I will try such simulation - I think it is also very related to "nonlinear" dependency in terms of categorical variables.  
I took an absolute value to sum of row + column, not to the column sum. But I will try column sum as well. These are very interesting observations.

**Comment by cshen6** [comment]
The simplest simulation is to just fill up the SC connectivity a bit, and
see what happens.

A model based simulation will be a 3 block model, from B=
[0.5,0.2,0.05;0.2,0.5,0.05;0.05,0.05,0.1].
The labels are 1,2,3.
Namely the first two blocks are kind of dense, but the last block is rarely
connected with the other two blocks.

If it fits our conjecture, nodes from the first two blocks should be
positive contributed, while nodes from the last block should be way
negative.

**Comment by youjin1207** [comment]
I [did simulation](https://github.com/neurodata/Multiscale-Network-Test/blob/master/Draft/outline.pdf) (a) using real data by adding edges one by one for Science group to any others and also (b) 3 block model. In the first case, significant negativity seems to disappear as I added one-two edges but negativity of pink group becomes evident. In the latter case, if you see **Figure 16**, block 3 having sparse edge distribution has negative contribution, but not monotonic to the power. 

My conjecture on this is : (a) contribution measure is relative measure, only valid within each example; (b) (Relatively) Sparse edge distribution usually leads to negative contribution.

**Comment by cshen6** [comment]
very cool! I think your conjecture is right.
