### ISSUE TITLE
organize GitHub folder

### ISSUE THREAD

**Issue by youjin1207** [neurodata/Multiscale-Network-Test#28]
- [ ] clear up unnecessary files.
- [ ] set aside unused figures / code.
- [ ] upload every relevant codes used in a draft.
- [ ] synchronize with overleaf.

**Comment by cshen6** [comment]
I re-organized the draft folder, so I can easily link up with the overleaf version.

Can you check out if I messed up any of your recent change in tex (draft/network-testing)?

there are also some error msgs and missing figures, please fix? thanks!

**Comment by youjin1207** [comment]
I fixed the error and tried to merge them. But let's leave .sty file for now, until I could download full latex packages...
